### PR TITLE
Add completion hint so shells understand they can complete with file names

### PR DESCRIPTION
**Pull request by alerque**
Correct implementation of #157

### CODE REVIEW

**Comment by bensadeh** [comment]
Hi and thanks for the PR! 

This is great, I wasn't aware of this feature. 

However, wouldn't `AnyPath` be more appropriate given that we support opening both files as well as folders?

https://docs.rs/clap/latest/clap/enum.ValueHint.html

**Comment by alerque** [comment]
As a matter of fact yes, that would be better. I just amended my commit in this PR. I don't use that mode in my workflows and so it didn't cross my mind.

**Comment by bensadeh** [comment]
Great! Thanks for putting this PR together!

**Comment by alerque** [comment]
Would you consider a patch release? This isn't huge but the symlink handling fix still isn't released either after months, and nothing big *is* in the works that I see. Little quality of life improvements shouldn't be held up forever waiting os the next big thing to land if it isn't even on the horizon ... in my way of thinking.

**Comment by bensadeh** [comment]
I'm happy to do a patch release. 

There is, however, no symlink handling fix in the pipeline because I was ultimately not able to reproduce the issue in https://github.com/bensadeh/tailspin/issues/134. 

If you are have symlinking problems, I'd be glad to take a look at it in a new issue with a minimally reproducible example.

**Comment by alerque** [comment]
I have some memory of having had an issue and having seen commit activity about it and wrote it off to try later, but I do *not* remember what my specific case was and I don't see anything handy right now that suggests what I might have been doing. Sorry for the confusion, I'll be sure to report more specifically if I run across anything now.

**Comment by bensadeh** [comment]
No problem at all. From my own testing, I remember being able to resolve symlinking, however I also know that both the error messages and error handling can be improved as well, so it might be symptomatic of a need to improve them as well.

**Pull request merged**
